apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-dz2
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /health
        pathType: Exact
        backend:
          service:
            name: otus-dz2
            port:
              number: 80