@startuml Регистрация_пользователя
title 1 Регистрация пользователя
    actor Покупатель
    participant API_Gateway #ff9e4f
    participant Auth_Service #4fafff
    participant Notification_Service #8aff4f
    participant MongoDB #13aa52

    Покупатель ->> API_Gateway: POST /auth/register
    API_Gateway ->> Auth_Service++: gRPC RegisterUser()
    Auth_Service ->> MongoDB++: Сохранить пользователя
    Auth_Service <<-- MongoDB--: OK
    Auth_Service -->> API_Gateway--: 201 Created + JWT
    API_Gateway ->> Notification_Service: Kafka: UserRegistered
    API_Gateway -->> Покупатель: Успешная регистрация
    Notification_Service -->> Покупатель: Email с подтверждением
    
@enduml
